sudo: false
dist: trusty
language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - openjdk8
  - openjdk7

script: mvn -B clean install

deploy:
  provider: script
  script: "./travis/deploy.sh"
  skip_cleanup: true
  on:
    branch: master
