version: 2
jobs:
  jdk8:
    working_directory: ~/ci
    docker:
    - image: debian:buster

    steps:
    - run: apt-get update -qq && apt-get install -qqy git unzip ssh ca-certificates tar gzip
    - checkout

    - run:
        name: Installing Java
        command: apt-get install -qqy openjdk-8-jdk-headless

    - restore_cache:
        keys:
        - m2-{{ checksum "pom.xml" }}
        - m2-

    - run:
        name: Running tests
        command: bash ./.circleci/test.sh

    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
        when: always

    - store_test_results:
        path: ~/junit

    - save_cache:
        paths:
        - ~/.m2
        key: m2-{{ checksum "pom.xml" }}
  jdk11:
    working_directory: ~/ci
    docker:
    - image: debian:buster

    steps:
    - run: apt-get update -qq && apt-get install -qqy git unzip ssh ca-certificates tar gzip
    - checkout

    - run:
        name: Installing Java
        command: apt-get install -qqy openjdk-11-jdk-headless

    - restore_cache:
        keys:
        - m2-{{ checksum "pom.xml" }}
        - m2-

    - run:
        name: Running tests
        command: bash ./.circleci/test.sh

    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
        when: always

    - store_test_results:
        path: ~/junit

    - save_cache:
        paths:
        - ~/.m2
        key: m2-{{ checksum "pom.xml" }}


  deploy:
    working_directory: ~/ci
    docker:
    - image: debian:buster

    steps:
    - run: apt-get update -qq && apt-get install -qqy git unzip ssh ca-certificates tar gzip
    - checkout

    - restore_cache:
        keys:
        - m2-{{ checksum "pom.xml" }}
        - m2-

    - attach_workspace:
        at: ~/ci

    - run:
        name: Deploying
        command: bash ./.circleci/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - jdk8:
        filters:
          branches:
            ignore: master

    - jdk11:
        filters:
          branches:
            ignore: master

    - deploy:
        filters:
          branches:
            only: master
