on: pull_request
name: Pull Requests
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        jdk: [ 11, 17, 21 ]
    name: JDK ${{ matrix.jdk }} on ${{ matrix.os }}.
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          cache: "maven"
          distribution: "corretto"
      - run: mvn -B clean package
        env:
          SCANII_CREDS: ${{ secrets.SCANII_CREDS }}
